// <auto-generated />
using System;
using JMBackup.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JMBackup.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JMBackupDbContext))]
    [Migration("20260820023105_AddFileIndex")]
    partial class AddFileIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("JMBackup.Domain.Entities.FileIndexEntry", b =>
                {
                    b.Property<string>("TaskName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastBackedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskName", "RelativePath");

                    b.HasIndex("TaskName");

                    b.ToTable("FileIndex", (string)null);
                });

            modelBuilder.Entity("JMBackup.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
